arm:
	g++ -march=native -mtune=native -Wall -Wextra -Wno-deprecated-copy -Ofast -fno-strict-aliasing -ftree-vectorize -flto -c oldbloom/bloom.cpp -o oldbloom.o
	g++ -march=native -mtune=native -Wall -Wextra -Wno-deprecated-copy -Ofast -fno-strict-aliasing -ftree-vectorize -flto -c bloom/bloom.cpp -o bloom.o
	gcc -march=native -mtune=native -Wall -Wextra -Wno-unused-parameter -Ofast -fno-strict-aliasing -ftree-vectorize -c base58/base58.c -o base58.o
	gcc -march=native -mtune=native -Wall -Wextra -Ofast -fno-strict-aliasing -ftree-vectorize -c rmd160/rmd160.c -o rmd160.o
	g++ -march=native -mtune=native -Wall -Wextra -Wno-deprecated-copy -Ofast -fno-strict-aliasing -ftree-vectorize -c sha3/sha3.c -o sha3.o
	g++ -march=native -mtune=native -Wall -Wextra -Wno-deprecated-copy -Ofast -fno-strict-aliasing -ftree-vectorize -c sha3/keccak.c -o keccak.o
	gcc -march=native -mtune=native -Wall -Wextra -Ofast -fno-strict-aliasing -ftree-vectorize -c xxhash/xxhash.c -o xxhash.o
	g++ -march=native -mtune=native -Wall -Wextra -Wno-deprecated-copy -Ofast -fno-strict-aliasing -ftree-vectorize -c util.c -o util.o
	g++ -march=native -mtune=native -Wall -Wextra -Wno-deprecated-copy -Ofast -fno-strict-aliasing -ftree-vectorize -c secp256k1/Int.cpp -o Int.o
	g++ -march=native -mtune=native -Wall -Wextra -Wno-deprecated-copy -Ofast -fno-strict-aliasing -ftree-vectorize -c secp256k1/Point.cpp -o Point.o
	g++ -march=native -mtune=native -Wall -Wextra -Wno-deprecated-copy -Ofast -fno-strict-aliasing -ftree-vectorize -c secp256k1/SECP256K1.cpp -o SECP256K1.o
	g++ -march=native -mtune=native -Wall -Wextra -Wno-deprecated-copy -Ofast -fno-strict-aliasing -ftree-vectorize -c secp256k1/IntMod.cpp -o IntMod.o
	g++ -march=native -mtune=native -Wall -Wextra -Wno-deprecated-copy -Ofast -fno-strict-aliasing -ftree-vectorize -flto -c secp256k1/Random.cpp -o Random.o
	g++ -march=native -mtune=native -Wall -Wextra -Wno-deprecated-copy -Ofast -fno-strict-aliasing -ftree-vectorize -flto -c secp256k1/IntGroup.cpp -o IntGroup.o
	g++ -march=native -mtune=native -Wall -Wextra -Wno-deprecated-copy -Ofast -fno-strict-aliasing -o hash/ripemd160.o -ftree-vectorize -flto -c hash/ripemd160.cpp
	g++ -march=native -mtune=native -Wall -Wextra -Wno-deprecated-copy -Ofast -fno-strict-aliasing -o hash/sha256.o -ftree-vectorize -flto -c hash/sha256.cpp
	g++ -march=native -mtune=native -Wall -Wextra -Wno-deprecated-copy -Ofast -fno-strict-aliasing -o hash/ripemd160_sse.o -ftree-vectorize -flto -c hash/ripemd160_sse.cpp
	g++ -march=native -mtune=native -Wall -Wextra -Wno-deprecated-copy -Ofast -fno-strict-aliasing -o hash/sha256_sse.o -ftree-vectorize -flto -c hash/sha256_sse.cpp
	g++ -march=native -mtune=native -Wall -Wextra -Wno-deprecated-copy -Ofast -fno-strict-aliasing -ftree-vectorize -o keyhunt keyhunt.cpp base58.o rmd160.o hash/ripemd160.o hash/ripemd160_sse.o hash/sha256.o hash/sha256_sse.o bloom.o oldbloom.o xxhash.o util.o Int.o  Point.o SECP256K1.o  IntMod.o  Random.o IntGroup.o sha3.o keccak.o  -lm -lpthread
	rm -r *.o
